server:
  port: 8001
spring:
  application:
    name: spring-cloud-config-server
  cloud:
    config:
      server:
        git:
          uri: https://github.com/Jesse-so-cool/spring-cloud-project/
          search-paths: config-repository
eureka:
  client:
    service-url:
      defaultZone: http://localhost:8000/eureka/