server:
  port: 8001
spring:
  application:
    name: jesse-config
  cloud:
    config:
      server:
        git:
          uri: https://github.com/Jesse-so-cool/spring-cloud-project/    # 配置git仓库的地址
          search-paths: config-repository                           # git仓库地址下的相对地址，可以配置多个，用,分割。
          #username:                                             # git仓库的账号
          #password:                                             # git仓库的密码
eureka:
  client:
    service-url:
      defaultZone: http://localhost:8000/eureka/