spring:
  application:
    name: jesse-zuul
server:
  port: 8900

zuul:
  routes:
    baidu:
      path: /it/**
      url: http://www.ityouknow.com/

eureka:
  client:
    register-with-eureka: false
    fetch-registry: false
    service-url:
      defaultZone: http://localhost:8000/eureka/